#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml
app_file:
    # loads routes from the given routing file stored in some bundle
    resource: '@AdminBundle/Resources/config/routing.yaml'

app_annotations:
    # loads routes from the PHP annotations of the controllers found in that directory
    resource: '../src/Acme/AdminBundle/Controller/'
    type:     annotation

#app_directory:
    # loads routes from the YAML or XML files found in that directory
#    resource: '../legacy/routing/'
#    type:     directory

app_bundle:
    # loads routes from the YAML or XML files found in some bundle directory
    resource: '@AdminBundle/Resources/public/'
    type:     directory